<form  action="edit.php" class="w-1/3 h-2/3 flex flex-col justify-around items-center" onsubmit="return confirm('確認修改資料?'); " method="post">
<input type="hidden" name="employee_id" value="<?= $employee_id ?>">
    <h2 class="text-4xl text-cyan-900 self-center">基本資料</h2>
    <label class="text-lg m-1">員工名稱:<input id="name" class="text-lg border-2 border-gray-300 p-2 rounded-sm outline-2 outline-cyan-900 m-1" name="name" type="text"  value="<?= $search_basic_data_result["employee_name"] ?>"></label>
    <label class="text-lg m-1">員工電話:<input id="name" class="text-lg border-2 border-gray-300 p-2 rounded-sm outline-2 outline-cyan-900 m-1" name="phone" type="text"  value="<?= $search_basic_data_result["employee_phone"] ?>"></label>
    <label class="text-lg m-1">員工到職日期:<input id="name" class="text-lg border-2 border-gray-300 p-2 rounded-sm outline-2 outline-cyan-900 m-1" name="onboard_date" type="date"  value="<?= $search_basic_data_result["employee_onboard_date"] ?>"></label>
    <label class="text-lg m-1">員工在職狀態:<input type="radio" name="status" value="1" class="text-lg border-2 border-gray-300 p-2 rounded-sm outline-2 outline-cyan-900 m-1" <?php if(isset($search_basic_data_result['employee_still_onboard']) && $search_basic_data_result['employee_still_onboard']==1){echo 'checked';} ?>/><label class="text-lg m-1">仍在職</label><input type="radio" name="status" value="0" class="text-lg border-2 border-gray-300 p-2 rounded-sm outline-2 outline-cyan-900 m-1" <?php if(isset($search_basic_data_result['employee_still_onboard']) && $search_basic_data_result['employee_still_onboard']==0){echo 'checked';} ?>/><label class="text-lg m-1">已離職</label></label>
    <label class="text-lg m-1">員工信箱:<input id="name" class="text-lg border-2 border-gray-300 p-2 rounded-sm outline-2 outline-cyan-900 m-1" name="email" type="text"  value="<?= $search_basic_data_result["employee_email"] ?>"></label>
    <button type="submit" class="text-xl rounded-sm border-2 border-gray-300 bg-cyan-100 p-2 text-cyan-900" > 修改 </button>
    </form>